events {
    worker_connections 1024;
}

stream {
    server {
        listen 4433;
        proxy_ssl on;
        proxy_ssl_protocols TLSv1.3;
        
        proxy_ssl_certificate /opt/nginx/certs/falcon512.crt;
        proxy_ssl_trusted_certificate /opt/nginx/certs/falcon512.crt;
        
        proxy_pass SERVER_IP_PLACEHOLDER:4433;
    }
}
