events {
    worker_connections 1024;
}

stream {
    upstream v2ray_backend {
        server 172.17.0.1:443; 
    }

    server {
        listen 4433 ssl;
        ssl_protocols TLSv1.3;
        
        ssl_certificate /opt/nginx/certs/falcon512.crt;
        ssl_certificate_key /opt/nginx/certs/falcon512.key;
        
        proxy_pass v2ray_backend;
    }
}
